spring:
  application.name: todo-backend
  reactor.context-propagation: auto
  threads.virtual.enabled: true
  docker.compose:
    lifecycle-management: start-only
    file: "../../../docker-compose.yml"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "readinessState,ping,diskSpace"

MONGO_CONNECTION_URI: mongodb://localhost:27017
