spring:
  threads.virtual.enabled: true
  docker.compose.lifecycle-management: start-only

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "readinessState,ping,diskSpace"

MONGO_CONNECTION_URI: mongodb://localhost:27017
